# this script plots the ERPs based on the csv file generated by MATLAB
# the csv file is written by the MATLAB function "NEW_GRAND_AVERAGE.m"

library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)
library(gplots)

estimatorVector <- c("CLred", "CWred", "SYL", "CLnored", "CWnored")
newlabels <- c( "CLall", "CWall", "SYL", "CW", "CL")

N1er = list()
N1RE = list()
i = 0
hhh = 0
for (estimator in estimatorVector){
  hhh <- hhh + 1
filename <- paste("ERPs", estimator, ".csv", sep = "")
erp <- read.csv(filename)
i = i + 1
Them <- theme(axis.title.x=element_blank(), axis.text.x = element_blank(), 
              axis.title.y=element_blank(), axis.text.y = element_blank(),
              legend.position="none",
              panel.grid.minor = element_line(colour="black", size=0.1, linetype = "dotted"),
              panel.grid.major = element_line(colour="black", size=0.1, linetype = "dashed"))
Them2 <- theme(axis.title.y = element_text(angle = 0, vjust=1),
               legend.position="none")
               # panel.grid.major=element_line(colour="lightgrey"))
N1er[[i]] <- ggplot(data=erp, aes(x=times)) +
  geom_line(aes(y=mu_N1_er_low, color = "low")) +
  geom_line(aes(y=mu_N1_er_mid, color = "medium")) +
  geom_line(aes(y=mu_N1_er_high, color = "high")) +
  scale_color_discrete(name="WM load",
                      breaks=c("low", "medium", "high"),
                      labels=c("low", "medium", "high")) +
  scale_y_continuous(limits = c(-1.7, 1.2)) +
  scale_x_continuous(breaks = c(-100, 0, 100,200,300,400,500)) +
  labs(x="times", y=expression(paste(mu, "V"))) +
  Them +
  ggtitle(newlabels[hhh])
N1RE[[i]] <- ggplot(data=erp, aes(x=times)) +
  geom_line(aes(y=mu_N1_RE_low, color = "low")) +
  geom_line(aes(y=mu_N1_RE_mid, color = "medium")) +
  geom_line(aes(y=mu_N1_RE_high, color = "high")) +
  scale_color_discrete(name="WM load", 
                       breaks=c("low", "medium", "high"),
                       labels=c("low", "medium", "high")) +
  scale_y_continuous(limits = c(-1.7, 1.2)) +
  scale_x_continuous(breaks = c(-100, 0, 100,200,300,400,500)) +
  labs(x="times", y=expression(paste(mu, "V"))) +
  Them +
  ggtitle(newlabels[hhh])
}

# plot_grid(N1er, N1RE, labels = c("A", "B"), ncol = 2, nrow = 1)

# create a leged for the erp plots:
erp_legend <- erp
erp_legend$mu_N1_er_low[1:150] = -10
erp_legend$mu_N1_er_mid[1:150] = -10
erp_legend$mu_N1_er_high[1:150] = -10
erp_legend$mu_N1_RE_high[1:150] = -10
erp_legend$mu_N1_RE_low[1:150] = -10
erp_legend$mu_N1_RE_mid[1:150] = -10
Sc <- ggplot(data=erp_legend, aes(x=times)) +
  geom_line(aes(y=mu_N1_RE_low, color = "low")) +
  geom_line(aes(y=mu_N1_RE_mid, color = "medium")) +
  geom_line(aes(y=mu_N1_RE_high, color = "high")) +
  scale_color_discrete(name="WM load", 
                       breaks=c("low", "medium", "high"),
                       labels=c("low", "medium", "high")) +
  scale_y_continuous(limits = c(-1.7, 1.2),
                     minor_breaks = seq(-1, 1, 0.5),
                     breaks = seq(-1, 1, 1)) +
  scale_x_continuous(minor_breaks = seq(-50,500, 50),
                       breaks = seq(-100,500, 100)) +
  labs(x="times", y=expression(paste(mu, "V"))) +
  theme(axis.title.y = element_text(angle = 0, vjust=1),
        legend.position=c(.5, .5),
        panel.grid.minor = element_line(colour="black", size=0.1, linetype = "dotted"),
        panel.grid.major = element_line(colour="black", size=0.1, linetype = "dashed"))

N1er[[6]] <- Sc
N1RE[[6]] <- Sc + Them + theme(axis.line = element_blank(),
                               axis.ticks = element_blank(),
                               panel.grid = element_blank(),
                               panel.grid.minor = element_blank(),
                               panel.grid.major = element_blank())

ee <- list()
ee <- rbind(N1er, N1RE)
plot_grid(plotlist = ee, nrow = 6, ncol = 2, labels = c("E-R", "R-E", "", "", "", "", "", "", "", ""), align = "v")


